TABLENAME : GAMESCORE
COLUMN1 : MEMBER_ID (PK, FK)
COLUMN2 : GAME_NUM
COLUMN3 : EASY
COLUMN4 : NORMAL
COLUMN5 : HARD

DROP TABLE GAMESCORE

CREATE TABLE GAMESCORE (
	MEMBER_ID VARCHAR2(50) NOT NULL,
	GAME_NUM NUMBER(3) DEFAULT -1,
	EASY NUMBER(5) DEFAULT -1,
	NORMAL NUMBER(5) DEFAULT -1,
	HARD NUMBER(5) DEFAULT -1,
	CONSTRAINT MEMBER_SCORE_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE
)